# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "toradex-flasher"
BBFILE_PATTERN_toradex-flasher = "^${LAYERDIR}/"
BBFILE_PRIORITY_toradex-flasher = "25"

LAYERDEPENDS_toradex-flasher = "core"
LAYERSERIES_COMPAT_toradex-flasher = "scarthgap"
